### ISSUE TITLE
Database issue

### ISSUE THREAD

**Issue by SamyamJungThapa** [subinkhadka/Shoe-Ecommerce#7]
It looks like some of the schemas has not been set properly. Work on it

**Comment by Aayushthapa10** [comment]
onst userSchema = mongoose.Schema(
  {
    name: {
      type: String,
      required: true,
    },
    email: {
      type: String,
      required: true,
      unique: true,
    },
    password: {
      type: String,
      required: true,
    },
    isAdmin: {
      type: Boolean,
      required: true,
      default: false,
    },
[(No Title)](https://www.facebook.com/)
